default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: penny_development

test:
  <<: *default
  database: penny_test

production:
  <<: *default
  database: penny_production